In [ ]:
#pip install geopy

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from my_defs import* 

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [2]:
data_down = pd.read_csv('Data_down.csv', sep='\s+')   #your oath here 
data_up = pd.read_csv('Data_up.csv', sep='\s+')    #your oath here

# Datetime-related features

In [3]:
# Converting rawTimesamp from Unix to Datetime
data_up['date'] = data_up['rawTimesamp'] 
data_down['date'] = data_down['rawTimesamp']

data_down['rawTimesamp'] = data_down['rawTimesamp'].map(   #adding '%Y-%m-%d %H:%M:%S'
    lambda x: unix_to_datetime(x))   # function in my_defs

data_up['rawTimesamp'] = data_up['rawTimesamp'].map(
    lambda x: unix_to_datetime(x)) # function in my_defs


data_down['date'] = data_down['date'].map(    #adding '%Y-%m-%d'
    lambda x: unix_to_date(x))   # function in my_defs

data_up['date'] = data_up['date'].map(
    lambda x: unix_to_date(x))   # function in my_defs

In [4]:
#checking data types after date-transformations
print('Download Data Types\n',data_down.dtypes)
print('Upload Data Types\n',data_up.dtypes)

Download Data Types
 timestamp             float64
rawTimesamp    datetime64[ns]
distance              float64
lat                   float64
lon                   float64
alt                   float64
speed                 float64
acc                   float64
dir                   float64
connected               int64
rsrp                    int64
rsrq                    int64
sinr                    int64
cqi                     int64
ss                      int64
ta                      int64
ci                      int64
pci                     int64
id                      int64
payload               float64
throughput            float64
rtt                     int64
measurement             int64
location               object
date           datetime64[ns]
dtype: object
Upload Data Types
 timestamp             float64
rawTimesamp    datetime64[ns]
distance              float64
lat                   float64
lon                   float64
alt                   float64
speed                 float64
acc                   float64
dir                   float64
connected               int64
rsrp                    int64
rsrq                    int64
sinr                    int64
cqi                     int64
ss                      int64
ta                      int64
ci                      int64
pci                     int64
id                      int64
payload               float64
throughput            float64
rtt                     int64
txPower               float64
measurement             int64
location               object
date           datetime64[ns]
dtype: object

In [5]:
# generating the cols: hour, week, year, dayofweek, dayofmonth and month
# and categorically encoding daytime


# the definition 'encode_day_time_cat' calls 'featurize_datetime' inside it  

data_up = encode_day_time_cat(data_up, 'hour', 'day_time')   # function in my_defs
data_down = encode_day_time_cat(data_down, 'hour', 'day_time')   # function in my_defs

data_up

,timestamp,rawTimesamp,distance,lat,lon,alt,speed,acc,dir,connected,rsrp,rsrq,sinr,cqi,ss,ta,ci,pci,id,payload,throughput,rtt,txPower,measurement,location,date,hour,week,year,dayofweek,dayofmonth,month,day_time
0,11.53,2018-12-10 10:08:58,113.75,51.490592,7.414306,156.39,12.21,0.50,77.59,1,-85,-5,22,10,50,7,26385408,95,0,4.0,24.52110,35,12.30470,1544432927,campus,2018-12-10,10,50,2018,0,10,12,2
1,21.33,2018-12-10 10:09:08,231.40,51.490717,7.415835,152.53,11.17,0.00,87.24,1,-84,-6,11,13,52,4,29391105,167,1,2.0,14.85610,51,10.01560,1544432927,campus,2018-12-10,10,50,2018,0,10,12,2
2,32.22,2018-12-10 10:09:19,323.73,51.490634,7.417138,154.23,6.44,0.00,48.55,1,-82,-6,21,15,54,4,29391105,167,2,4.0,16.26840,57,4.34375,1544432927,campus,2018-12-10,10,50,2018,0,10,12,2
3,54.69,2018-12-10 10:09:42,537.34,51.492531,7.416222,154.41,12.33,0.02,336.68,1,-90,-6,16,9,45,4,29391105,167,4,8.0,14.58860,60,17.31250,1544432927,campus,2018-12-10,10,50,2018,0,10,12,2
4,63.98,2018-12-10 10:09:51,650.07,51.493484,7.415836,153.05,11.69,-0.18,348.09,1,-101,-10,13,15,40,4,29391105,167,5,6.0,13.12550,57,19.93750,1544432927,campus,2018-12-10,10,50,2018,0,10,12,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,422.52,2019-01-18 10:22:11,2914.37,51.510185,7.461754,159.96,6.28,0.00,135.25,1,-89,-7,7,7,49,1,26378755,441,41,5.0,21.36750,48,17.82810,1547802908,urban,2019-01-18,10,3,2019,4,18,1,2
2138,434.11,2019-01-18 10:22:22,3007.72,51.509847,7.463047,155.79,6.32,0.00,101.37,1,-85,-7,10,8,53,5,27299332,326,42,8.0,18.77380,46,17.11720,1547802908,urban,2019-01-18,10,3,2019,4,18,1,2
2139,442.91,2019-01-18 10:22:31,3053.18,51.509741,7.463746,147.95,6.77,1.34,118.12,1,-82,-5,20,10,55,5,27299332,326,43,9.0,31.81620,42,11.07810,1547802908,urban,2019-01-18,10,3,2019,4,18,1,2
2140,451.53,2019-01-18 10:22:40,3128.44,51.509786,7.464816,150.03,10.24,0.00,93.22,1,-90,-7,10,6,46,5,27299332,326,44,2.0,17.44820,36,17.28130,1547802908,urban,2019-01-18,10,3,2019,4,18,1,2
2141,461.08,2019-01-18 10:22:49,3243.56,51.509743,7.466608,154.59,11.65,0.00,94.90,1,-93,-8,3,12,44,5,27299332,326,45,0.5,8.14664,42,18.96880,1547802908,urban,2019-01-18,10,3,2019,4,18,1,2

In [6]:
# generating the col rush_hour
'''
this first function returns 1 if time is between [06-09 or 16-19]
or 0 otherwise
'''
data_up['rush_hour'] = data_up['hour'].map(
    lambda x: 1 if x >= 6 and x< 9 else (1 if x >= 16 and x< 9 else 0 ))  
data_down['rush_hour'] = data_down['hour'].map(
    lambda x: 1 if x >= 6 and x< 9 else (1 if x >= 16 and x< 9 else 0 ))

In [7]:
def print_unique_values(dataset, u_col = ""):
    print('unique values', u_col , '=', len(data_down[u_col].unique()), '\n',
         data_down[u_col].unique(), '\n')

In [8]:
print_unique_values(data_down,u_col = "hour" )
print_unique_values(data_down,u_col = "week" )
print_unique_values(data_down,u_col = "dayofweek" )
print_unique_values(data_down,u_col = "month" )
print_unique_values(data_down,u_col = "dayofmonth" )

unique values hour = 7
 [10  9  6 14 15 12 13]

unique values week = 3
 [50 51  3]

unique values dayofweek = 5
 [0 1 2 3 4]

unique values month = 2
 [12  1]

unique values dayofmonth = 11
 [10 11 12 13 14 17 18 19 20 15 16]

In [9]:
print_unique_values(data_up,u_col = "hour" )
print_unique_values(data_up,u_col = "week" )
print_unique_values(data_up,u_col = "dayofweek" )
print_unique_values(data_up,u_col = "month" )
print_unique_values(data_up,u_col = "dayofmonth" )

unique values hour = 7
 [10  9  6 14 15 12 13]

unique values week = 3
 [50 51  3]

unique values dayofweek = 5
 [0 1 2 3 4]

unique values month = 2
 [12  1]

unique values dayofmonth = 11
 [10 11 12 13 14 17 18 19 20 15 16]

In [10]:
print('Upload Measurements count in 2018:',
      data_up[data_up['year'] == 2018].groupby('measurement').count().shape[0])

print('Upload Measurements count in 2019:',
      data_up[data_up['year'] == 2019].groupby('measurement').count().shape[0])

print('Download Measurements count in 2018:',
      data_down[data_down['year'] == 2018].groupby('measurement').count().shape[0])

print('Download Measurements count in 2019:',
      data_down[data_down['year'] == 2019].groupby('measurement').count().shape[0])

Upload Measurements count in 2018: 24
Upload Measurements count in 2019: 16
Download Measurements count in 2018: 24
Download Measurements count in 2019: 16

# Add Weather Features

In [11]:
weather_data = pd.read_csv('DE-8GBU_18_19.csv', parse_dates=['date'])
weather_data.head()

        date  tavg  tmin  tmax  prcp  snow  wdir  wspd  wpgt    pres  tsun
0 2018-01-01   6.8   4.3   9.0   7.2   0.0   NaN  24.0   NaN   999.6    67
1 2018-01-02   5.5   4.4   6.9  11.4   0.0   NaN  18.0   NaN  1007.1     9
2 2018-01-03   7.5   6.1  10.1   6.0   0.0   NaN  35.0   NaN   991.5    31
3 2018-01-04   8.0   7.0  11.1   1.9   0.0   NaN  25.0   NaN   994.6     0
4 2018-01-05   7.9   5.7   9.2   0.0   0.0   NaN  21.0   NaN   996.7     4

In [12]:
unique_dates = data_up['date'].unique()

In [13]:
weather_data.loc[weather_data['date'].isin(unique_dates)].describe()

,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
count,14.000000,14.000000,14.000000,14.000000,14.0,14.000000,14.000000,0.0,14.000000,14.000000
mean,4.035714,1.871429,5.942857,1.128571,0.0,196.357143,15.642857,NaN,1016.864286,100.785714
std,2.309381,2.459965,2.278905,1.938448,0.0,70.209146,5.569244,NaN,6.449402,121.889722
min,-0.200000,-3.100000,1.400000,0.000000,0.0,66.000000,6.000000,NaN,1003.300000,0.000000
25%,2.950000,0.925000,4.550000,0.000000,0.0,170.500000,11.500000,NaN,1011.850000,12.000000
50%,4.350000,1.600000,6.400000,0.100000,0.0,210.000000,16.000000,NaN,1018.500000,58.000000
75%,5.475000,3.100000,6.675000,1.300000,0.0,245.000000,20.750000,NaN,1022.100000,115.250000
max,7.500000,5.800000,9.700000,6.900000,0.0,288.000000,24.000000,NaN,1025.200000,412.000000

In [14]:
weather_data = weather_data.drop(['wpgt', 'snow'], axis = 1)

In [15]:
data_up = pd.merge(data_up,weather_data, how='inner', on='date' )
data_down = pd.merge(data_down,weather_data, how='inner', on='date')

# Location One-Hot Encoding

In [16]:
data_up = onehot_enc(data_up, 'location') # function in my_defs
data_down = onehot_enc(data_down, 'location')# function in my_defs

In [17]:
data_down

,timestamp,rawTimesamp,distance,lat,lon,alt,speed,acc,dir,connected,rsrp,rsrq,sinr,cqi,ss,ta,ci,pci,id,payload,throughput,rtt,measurement,date,hour,week,year,dayofweek,dayofmonth,month,day_time,rush_hour,tavg,tmin,tmax,prcp,wdir,wspd,pres,tsun,campus,highway,suburban,urban
0,10.33,2018-12-10 10:08:57,99.42,51.490553,7.413966,157.63,11.83,0.00,79.35,1,-85,-5,22,10,50,7,26385408,95,0,0.1,6.83763,41,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0
1,21.87,2018-12-10 10:09:09,237.43,51.490715,7.416002,152.41,10.76,-0.52,89.45,1,-84,-6,11,13,52,4,29391105,167,1,2.0,9.71463,58,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0
2,32.46,2018-12-10 10:09:19,325.26,51.490668,7.417176,154.64,6.19,-0.62,27.05,1,-82,-6,21,15,54,4,29391105,167,2,2.0,7.30594,57,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0
3,46.40,2018-12-10 10:09:33,448.27,51.491839,7.416804,155.87,9.77,-0.98,342.45,1,-94,-9,9,9,45,4,29391105,167,3,3.0,3.94997,163,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0
4,54.95,2018-12-10 10:09:42,540.48,51.492531,7.416222,154.41,12.33,0.01,336.68,1,-90,-6,16,9,45,4,29391105,167,4,5.0,8.54884,59,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2136,421.52,2019-01-18 10:22:10,2908.77,51.510228,7.461691,159.23,5.05,0.00,137.18,1,-89,-7,7,7,49,1,26378755,441,41,0.5,4.61894,48,1547802908,2019-01-18,10,3,2019,4,18,1,2,0,-0.2,-3.1,3.7,0.0,226.0,9.0,1019.1,412,0.0,0.0,0.0,1.0
2137,434.63,2019-01-18 10:22:23,3010.99,51.509847,7.463047,155.79,6.32,0.00,101.37,1,-85,-7,10,8,53,5,27299332,326,42,10.0,19.87580,35,1547802908,2019-01-18,10,3,2019,4,18,1,2,0,-0.2,-3.1,3.7,0.0,226.0,9.0,1019.1,412,0.0,0.0,0.0,1.0
2138,441.33,2019-01-18 10:22:30,3044.81,51.509787,7.463589,150.10,4.93,0.00,109.23,1,-82,-5,20,10,55,5,27299332,326,43,0.5,5.87372,43,1547802908,2019-01-18,10,3,2019,4,18,1,2,0,-0.2,-3.1,3.7,0.0,226.0,9.0,1019.1,412,0.0,0.0,0.0,1.0
2139,453.15,2019-01-18 10:22:41,3146.50,51.509798,7.465158,151.15,11.74,0.00,95.13,1,-90,-7,10,6,46,5,27299332,326,44,5.0,15.72950,69,1547802908,2019-01-18,10,3,2019,4,18,1,2,0,-0.2,-3.1,3.7,0.0,226.0,9.0,1019.1,412,0.0,0.0,0.0,1.0
2140,460.73,2019-01-18 10:22:49,3239.49,51.509750,7.466438,154.61,11.71,0.00,96.02,1,-93,-8,3,12,44,5,27299332,326,45,0.1,5.12822,38,1547802908,2019-01-18,10,3,2019,4,18,1,2,0,-0.2,-3.1,3.7,0.0,226.0,9.0,1019.1,412,0.0,0.0,0.0,1.0

# Adding Rolling Features

In [18]:
rolling_down = data_down[['rawTimesamp', 'measurement',
                          'throughput']].sort_values(by=['measurement','rawTimesamp'] )
rolling_up = data_up[['rawTimesamp', 'measurement', 
                      'throughput']].sort_values(by=['measurement','rawTimesamp'] )

In [19]:
rolling_down = means_and_std(rolling_down,rolling_col = 'measurement',
                            target_col = 'throughput')  # function in my_defs
rolling_up = means_and_std(rolling_up, rolling_col = 'measurement',
                           target_col = 'throughput')# function in my_defs

In [20]:
# function in my_defs
rolling_down = shift_group_features_(rolling_down, group_by ='measurement',
                                  shift_col1 = "throughput_mean", shift_col2 = "throughput_std",
                                    shift_col3 = "throughput_var")
# function in my_defs
rolling_up = shift_group_features_(rolling_up, group_by ='measurement',
                               shift_col1 = "throughput_mean", shift_col2 = "throughput_std",
                                    shift_col3 = "throughput_var")

In [21]:
data_down = pd.merge(data_down,rolling_down, how='inner')
data_up = pd.merge(data_up,rolling_up, how='inner')
data_down.head()

,timestamp,rawTimesamp,distance,lat,lon,alt,speed,acc,dir,connected,rsrp,rsrq,sinr,cqi,ss,ta,ci,pci,id,payload,throughput,rtt,measurement,date,hour,week,year,dayofweek,dayofmonth,month,day_time,rush_hour,tavg,tmin,tmax,prcp,wdir,wspd,pres,tsun,campus,highway,suburban,urban,throughput_mean,throughput_std,throughput_var
0,10.33,2018-12-10 10:08:57,99.42,51.490553,7.413966,157.63,11.83,0.00,79.35,1,-85,-5,22,10,50,7,26385408,95,0,0.1,6.83763,41,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
1,21.87,2018-12-10 10:09:09,237.43,51.490715,7.416002,152.41,10.76,-0.52,89.45,1,-84,-6,11,13,52,4,29391105,167,1,2.0,9.71463,58,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0,6.837630,0.000000,0.000000
2,32.46,2018-12-10 10:09:19,325.26,51.490668,7.417176,154.64,6.19,-0.62,27.05,1,-82,-6,21,15,54,4,29391105,167,2,2.0,7.30594,57,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0,8.276130,2.034346,4.138564
3,46.40,2018-12-10 10:09:33,448.27,51.491839,7.416804,155.87,9.77,-0.98,342.45,1,-94,-9,9,9,45,4,29391105,167,3,3.0,3.94997,163,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0,7.952733,1.543709,2.383038
4,54.95,2018-12-10 10:09:42,540.48,51.492531,7.416222,154.41,12.33,0.01,336.68,1,-90,-6,16,9,45,4,29391105,167,4,5.0,8.54884,59,1544432927,2018-12-10,10,50,2018,0,10,12,2,0,4.4,3.1,5.6,1.3,265.0,24.0,1018.7,59,1.0,0.0,0.0,0.0,6.952043,2.365211,5.594221

# Add address  as OneHot Feature

In [22]:
'''
**This block of code may take quite some time till completion, depending on your internet speed 
(check my wall time in cell [25] before running it)

Don't want to wait ? :D 

Just navigate to the last cell of this section [29] and uncomment it to read and view our csv-files 
containing the one-hot-encoded addresses.
'''

"\n**This block of code may take quite some time till completion, depending on your internet speed \n(check my wall time in cell [25] before running it)\n\nDon't want to wait ? :D \n\nJust navigate to the last cell of this section [29] and uncomment it to read and view our csv-files \ncontaining the one-hot-encoded addresses.\n"

In [23]:
data_up['coordinates'] = list(zip(data_up.lat, data_up.lon))
data_down['coordinates'] = list(zip(data_down.lat, data_down.lon))

In [ ]:
%%time
data_up['dist'] = data_up['coordinates'].map(
    lambda x:get_district(x)) # function in my_defs

data_down['dist'] = data_down['coordinates'].map(
    lambda x:get_district(x)) # function in my_defs 

data_up = data_up.drop(["coordinates"], axis =1 )
data_down = data_down.drop(["coordinates"], axis =1 )

In [ ]:
data_down

In [ ]:
data_down = onehot_enc(data_down, "dist") # function in my_defs
data_up = onehot_enc(data_up, "dist") # function in my_defs

In [ ]:
# saving the data files as data_file_fat.csv in order to save time for next runs!

data_down.to_csv("data_down_fat.csv", index= False)  #your oath here
data_up.to_csv("data_up_fat.csv", index = False)  #your oath here

In [24]:
'''
UNCOMMENT if you don't wanna wait to download the districts
and check your path if you get an error
'''

data_down = pd.read_csv("data_down_fat.csv", parse_dates = ["rawTimesamp", "date"])
data_up= pd.read_csv("data_up_fat.csv", parse_dates = ["rawTimesamp", "date"])
#display(data_down.head())
#display(data_up.head())

# Pysical Cell ID Encoding

In [25]:
data_down = onehot_enc(data_down, 'pci')
data_up = onehot_enc(data_up, 'pci')

In [26]:
# data_up_full.csv & data_down_full.csv  have all the generated features.
# all undesired features will be right before modeling dropped


data_up.to_csv("data_up_full.csv", index = False)  #your path here

data_down.to_csv("data_down_full.csv", index= False)  #your path here